version: "3.9"
services:
  whatsapp-gateway:
    build: .
    image: whatsapp-gateway:dev
    container_name: whatsapp-gateway-dev
    ports:
      - "8087:8080"
    environment:
      - PUPPETEER_SKIP_DOWNLOAD=true
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ./:/app
      - /app/node_modules
      - ./data.db:/app/data.db       # SQLite DB (opsional, kalau pakai)
      - ./.env:/app/.env             # .env file
    command: /bin/sh -c "npx prisma generate && npm run dev"
